name: Go
on: [push]
jobs:
  build:
    name: Check for broken links
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
    - uses: actions/checkout@v2
    - run: |
         go install github.com/raviqqe/muffet@v1.5.7
         muffet -v https://blog.nolanemirot.com --exclude="(safari-pinned-tab|twitter|x|ko-fi|linkedin|reddit|telegram|facebook|ycombinator)" --buffer-size 9000
