name: Go
on: [push, pull_request]
jobs:
  build:
    name: Check for broken links
    runs-on: ubuntu-latest
    container: golang:1.15-buster
    steps:
    - uses: actions/checkout@v2
    - run: |
         GO111MODULE=on go get -u github.com/raviqqe/muffet/v2
         muffet -v https://blog.nolanemirot.com --exclude="(safari-pinned-tab|twitter|ko-fi|linkedin)" --buffer-size 9000
