
name: Go
on: [push]
jobs:
  build:
    name: Check for misspell
    runs-on: ubuntu-latest
    container: golang:1.15-buster
    steps:
    - uses: actions/checkout@v2
    - run: |
         GO111MODULE=on go get -u github.com/client9/misspell/cmd/misspell@v0.3.4
         misspell -error misspell blog/content/posts/*.md  
